source 'https://rubygems.org'



gem 'rake'
gem 'pg' # PostgreSQL driver
gem 'sinatra'
gem 'activerecord', '~>4.1'

group :development do
  gem 'shotgun'
end

group :test do
  gem 'faker'
  gem 'rspec'
end
